### PR TITLE
Fixed ImageBitmap memory leak

### LINKED ISSUE #7850: Chrome browser tab page consumes lots of memory
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

After opening and closing several annotation jobs, the memory consumption rises from several hundred MBs (e.g., 200MB) to several GBs (e.g., 4GB).

### Expected Behavior

The memory consumption does not enlarge when switching to another annotation job on the same tab page.

### Possible Solution

After manually refreshing the tab page, the memory consumption drops to several hundred MBs.

### Context

_No response_

### Environment

```Markdown
- Git hash commit (`git log -1`): aecaba66db8c3a7cd5f17947318fa277471648f6
- Docker version `docker version` (e.g. Docker 17.0.05): 24.0.1
- Are you using Docker Swarm or Kubernetes?
No, I'm using Docker compose.
- Operating System and version (e.g. Linux, Windows, MacOS):
Linux: Ubuntu 20.04.3 LTS
```

### LINKED ISSUE #7909: RAM consumption
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

When labeling on `app.cvat.ai` using `SAM` after some amount of samples RAM consumption gets quite high and the page regularly crashes. 
image

### Expected Behavior

_No response_

### Possible Solution

My theory is that extracted image embeddings are stored in the cache, so I'd propose limiting the number of kept embeddings if that's the case

### Context

_No response_

### Environment

_No response_

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #7909
Resolved #7850

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Summary by CodeRabbit

- **Bug Fixes**
  - Addressed a significant memory leak issue by ensuring `ImageBitmap` objects are properly closed after use.
  - Updated various components to handle cleanup and termination of workers and instances correctly, preventing potential resource leaks.

- **Version Updates**
  - Updated `cvat-canvas` to version 2.20.3.
  - Updated `cvat-core` to version 15.0.6.
  - Updated `cvat-data` to version 2.1.0.

### CODE REVIEW

File: changelog.d/20240606_134734_boris_bitmap_memoryleak.md [hunk 1]
```diff
@@ -0,0 +1,4 @@
+### Fixed
+
+- Significant memory leak when ImageBitmap objects are not closed
```
Comment (bsekachev) [inline changelog.d/20240606_134734_boris_bitmap_memoryleak.md:3]:
```suggestion
- Significant memory leak related to the frames, which did not memory after become unused
```

**Review by azhavoro — APPROVED** [review]
