### PR TITLE
Fixed cannot read property 'annotations' of null

### LINKED ISSUE #7363: Cannot read properties of null (reading 'annotations')
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Open a job
2. Upload annotations to the job
3. Go to task page before upload is done
image

### Expected Behavior

_No response_

### Possible Solution

_No response_

### Context

_No response_

### Environment

```Markdown
v2.10.0
```

### LINKED ISSUE #7600: cvat-ui error when open a job with issues
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. create a issue in a job
2. open the job
3. go to the Jobs
4. click on the job I entered earlier

### Expected Behavior

_No response_

### Possible Solution

The error may be caused by HiddenIssueLabel.

### Context

error:
react-dom.production.min.js:209 Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Zl [as createPortal] (react-dom.production.min.js:287:319)
    at $Te (hidden-issue-label.tsx:65:12)
    at qi (react-dom.production.min.js:153:146)
    at ys (react-dom.production.min.js:261:496)
    at fl (react-dom.production.min.js:246:265)
    at dl (react-dom.production.min.js:246:194)
    at rl (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Va (react-dom.production.min.js:122:325)

### Environment

_No response_

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #7363
Also resolved #7600

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Summary by CodeRabbit

- **New Features**
  - Enhanced import functionalities to handle different types of instances like Job, Task, or Project.
  - Updated the application version to enhance user experience and system performance.

- **Bug Fixes**
  - Addressed an issue where uploading annotations could fail due to improper error handling.

- **Refactor**
  - Improved logic for closing jobs and handling dataset imports, ensuring smoother operations and user interactions.

- **Documentation**
  - Updated copyright year information to reflect the current period.

- **Chores**
  - Removed unnecessary code and updated dependencies to streamline the application's functionality.

### CODE REVIEW

File: cvat-ui/src/reducers/review-reducer.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ export default function (state: ReviewState = defaultState, action: any): Review
         }
         case AnnotationActionTypes.CLOSE_JOB:
         case AuthActionTypes.LOGOUT_SUCCESS: {
-            return { ...defaultState };
+            return defaultState;
```
Comment (klakhov) [inline cvat-ui/src/reducers/review-reducer.ts:200]: Should we apply such approach for all the default state actions? We have plenty of `return { ...defaultState }` in other places

**Review by klakhov — APPROVED** [review]
