### PR TITLE
Fix included frames handling on UI

### LINKED ISSUE #9097: Incorrect data returned in frames meta request for a ground truth job
### Actions before raising this issue

- [x] I searched the existing issues and did not find anything similar.
- [x] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task with Ground Truth job with attached archive.

Content of the image corresponds to the image number in this archive). Each image resolution is random. 

E.g. this is image_10.jpg. Its real resolution is 800x900
Image

2. Open GT job and check meta response. It has resolution 1500x900. The image distorsed

Image

Of course, image name also may be not correct: 

Image

[images.zip](https://github.com/user-attachments/files/18766802/images.zip)

### Expected Behavior

_No response_

### Possible Solution

_No response_

### Context

_No response_

### Environment

```Markdown

```

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Fixes #9097

- Added a temporary emulation in UI for the upcoming server changes in `/api/task|job/data/meta` `.frames`
- Updated related GT allocation table code
- Fixed type for the `included_frames` field in the related meta API response class

### How has this been tested?

[data_with_related_images.zip](https://github.com/user-attachments/files/19028777/data_with_related_images.zip)
[random_200.zip](https://github.com/user-attachments/files/19028782/random_200.zip)
[random_video_10s.mp4](https://github.com/user-attachments/assets/2e229289-13dc-43e5-9baa-c6361f4e312d)

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

File: cvat-core/src/frames.ts [hunk 1]
```diff
@@ -208,7 +208,23 @@ export class FramesMetaData {
             // it may be a videofile or one image
             framesInfo = frameNumbers.map(() => initialData.frames[0]);
         } else {
-            framesInfo = initialData.frames;
+            framesInfo = (() => {
+                if (initialData.frames.length > 1 &&
```
Comment (bsekachev) [inline cvat-core/src/frames.ts:212]: there is condition `initialData.frames.length === 1` above

Comment (bsekachev) [reply cvat-core/src/frames.ts:212]: The solution with frame names looks like a dirty hack
What to you think about this one?

```ts
            if (this.includedFrames?.length) {
                // only gt jobs have this.includedFrame, so this condition works only for them
                const framesIndexes = new Set(this.includedFrames.map((dataFrameNumber: number) => {
                    return Math.floor((dataFrameNumber - this.startFrame) / this.frameStep);
                }));
                framesInfo = initialData.frames.filter((_, idx) => framesIndexes.has(idx))
            } else {
                framesInfo = initialData.frames;
            }
```

File: cvat-core/src/frames.ts [hunk 2]
```diff
@@ -728,7 +744,9 @@ export async function getContextImage(jobID: number, frame: number): Promise<Rec
     const meta = await frameData.getMeta();
     const requestId = frame;
     const { jobStartFrame } = frameData;
-    const { related_files: relatedFiles } = meta.frames[frame - jobStartFrame];
+    const dataFrameNumber = meta.getDataFrameNumber(frame - jobStartFrame);
+    const frameIndex = meta.getFrameIndex(dataFrameNumber);
+    const { related_files: relatedFiles } = meta.frames[frameIndex];
```
Comment (bsekachev) [inline cvat-core/src/frames.ts:749]: Seems like a fix not related to the main PR, I will propose to create a separate pull request

File: cvat-core/src/frames.ts (hunk 1 above)
Comment (zhiltsov-max) [reply cvat-core/src/frames.ts:212]: > The solution with frame names looks like a dirty hack

Why it looks this way, if it's a constant defined by the server specifically for this?

> What to you think about this one?

The formula part `dataFrameNumber - this.startFrame` is not correct in cases with nonzero start frame and frame step. In meta `start_frame`, `stop_frame`, and `included_frames` contain input data frame numbers (absolute ones). The correct way would be to obtain the original data frame number, then find the corresponding `included_frames` index.

File: cvat-core/src/frames.ts (hunk 2 above)
Comment (zhiltsov-max) [reply cvat-core/src/frames.ts]: Ok, https://github.com/cvat-ai/cvat/pull/9162

File: cvat-core/src/frames.ts (hunk 1 above)
Comment (bsekachev) [reply cvat-core/src/frames.ts:212]: > Why it looks this way, if it's a constant defined by the server specifically for this?

Because as you mentioned, user may have files named `placeholder.jpg`, what potentially may lead to bugs
We should not consider such solutions

Comment (bsekachev) [reply cvat-core/src/frames.ts:212]: > The formula part dataFrameNumber - this.startFrame is not correct in cases with nonzero start frame and frame step

I tested it in this case, and it seems to work in cases with non-zero start frame and frame step !== 1. Not really understand from your explanation why it should not. 

> In meta `start_frame`, `stop_frame`, and `included_frames` contain input data frame numbers (absolute ones)

Yes. We want to map absolute frame number to segment frame number, using the formula above. 
Then, as for GT jobs meta returns info about all frames in the task, from 1st one, we do assumption, that frame number == frame index.

Comment (zhiltsov-max) [reply cvat-core/src/frames.ts]: Ok, looks good to me. Added some explanatory comments why it works.

**Review by bsekachev — APPROVED** [review]
