### PR TITLE
Fix: Gt annotations can be shown in standard mode

### LINKED ISSUE #8627: GT annotations can sometimes show up in the Standard mode
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

In a task with honeypots, GT annotations can show up in the UI, when an annotation job is just opened. It can happen on the first opening of the job or later. If a mode is switched, e.g. to Review, the GT annotations correctly disappear, until the show conflicts button is pressed.

image

### Expected Behavior

_No response_

### Possible Solution

_No response_

### Context

_No response_

### Environment

- bce96eaafd0dc1dab6d59044aba6e15f7ca3163e

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolves #8627

To reproduce the issue:
1. Create task with gt/honeypots
2. Add annotations to gt job
3. Go to normal job in review mode, enable show gt annotations
4. Go back to the task open the same job/another job
5. Gt annotations will be visible in standard mode
### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Summary by CodeRabbit

- **Bug Fixes**
	- Resolved an issue preventing ground truth annotations from displaying in standard mode.

- **Improvements**
	- Enhanced job closure functionality to reset ground truth visibility when a job is closed.
	- Improved handling of image filters to maintain the current processed image state upon successful job retrieval.

### CODE REVIEW

File: cvat-ui/src/reducers/settings-reducer.ts [hunk 1]
```diff
@@ -460,6 +459,7 @@ export default (state = defaultState, action: AnyAction): SettingsState => {
                 },
             };
         }
+        case AnnotationActionTypes.CLOSE_JOB:
```
Comment (bsekachev) [inline cvat-ui/src/reducers/settings-reducer.ts:462]: I would propose to use GET_JOB_SUCCESS instead
