### PR TITLE
Fix `random_per_job` option on create job page

### LINKED ISSUE #8599: `random_per_job` frame selection mode doesn't work on the job creation page
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task without quality checking configured
2. Open the task, open the job creation dialog (using the + button)
3. Select `random_per_job` frame selection method
4. Try to create a job

### Expected Behavior

Random per job mode is available on the job creation page.

### Possible Solution

_No response_

### Context

Should work similarly to the same option on the task creation page. The absolute number is equal to the percent value * task segment size.

### Environment

_No response_

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Newly introduced `random_per_job` option for frame selection method doesnt work properly on create job page. This patch fixes it.
Resolve #8599

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Release Notes

- **New Features**
	- Enhanced job initialization flexibility by allowing optional properties.
	- Improved job creation process with structured handling of job data.

- **Bug Fixes**
	- Adjusted loading spinner display logic for better user feedback during task fetching.

- **Documentation**
	- Updated copyright notice to reflect the year 2024.

- **Style**
	- Standardized property naming conventions across job-related interfaces for clarity.

### CODE REVIEW

File: cvat-ui/src/components/create-job-page/job-form.tsx [hunk 1]
```diff
@@ -86,24 +90,40 @@ function JobForm(props: Props): JSX.Element {
...
-    }, [taskSize]);
-    const frameCountDescription = 'A representative set, 5-15% of randomly chosen frames is recommended';
+    }, [taskSize, frameSelectionMethod, segmentSize]);
+
+    useEffect(() => {
+        const currentQuantity = form.getFieldValue('quantity');
+        onQuantityChange(currentQuantity);
+    }, [form, frameSelectionMethod]);
+
+    const setDescription = 'A representative set, 5-15% of randomly chosen frames is recommended';
```
Comment (bsekachev) [inline cvat-ui/src/components/create-job-page/job-form.tsx:126]:
```suggestion
    const description = 'A representative set, 5-15% of randomly chosen frames is recommended';
```

File: cvat-ui/src/components/create-job-page/job-form.tsx [hunk 2]
```diff
@@ -86,24 +90,40 @@ function JobForm(props: Props): JSX.Element {
         }
     };
 
+    const sizeBase = useCallback(() => {
+        if (frameSelectionMethod === FrameSelectionMethod.RANDOM) {
+            return taskSize;
+        }
+        return segmentSize;
+    }, [frameSelectionMethod, segmentSize, taskSize]);
```
Comment (bsekachev) [inline cvat-ui/src/components/create-job-page/job-form.tsx:98]: I do not think we need `useCallback` here as this function is not used as a prop somewhere

**Review by bsekachev — APPROVED** [review]
LGTM
