### PR TITLE
Stop editing when n key pressed

### LINKED ISSUE #5823: Adding points to existing polyline can not end
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1.draw a polyline
2.shift+click on one point of the polyline
3.I can add new point ,but cannot end the drawing when press N.

### Expected Behaviour

I can end the drawing when press N.
### Current Behaviour

cannot end the drawing.
### Context

The online https://app.cvat.ai/
### Your Environment

- Git hash commit (`git log -1`):
   The online https://app.cvat.ai/
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by KrishavRajSingh**
Fixes #5823 

When updating a polyline, one has to specifically click on the circle to end it. 

Changes made:
- Added an event listener to check for the 'n' key press during editing.
- When the 'n' key is detected and the shapeType is 'polyline', a `click` event is dispatched to the circle element to stop the polyline editing.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have updated the documentation accordingly
- [x] I have created a changelog fragment 
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Summary by CodeRabbit

- **New Features**
  - Enhanced editing functionality to support both MasksEditData and PolyEditData, providing more flexibility in the types of data that can be edited.

- **Improvements**
  - Updated user interface to reflect the new editing capabilities, including handling of polyline data.
  - Improved edit handling with new properties to manage editing states effectively.

- **Documentation**
  - Updated comments in the controls sidebar to clarify conditions for finishing edits.

### CODE REVIEW

File: cvat-canvas/src/typescript/editHandler.ts [hunk 1]
```diff
@@ -383,6 +385,18 @@ export class EditHandlerImpl implements EditHandler {
         this.release();
     }
 
+    private onNKeyUp = (e: KeyboardEvent): void => {
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/editHandler.ts:388]: It must be handled on `cvat-ui` level with mousetrap. 
Otherwise it cannot be configured.

- When shortcut caught in cvat-ui, it should call `canvasInstance.edit({enabled: false})`. 
- Canvas should handle correctly editing finish and trigger `canvas.edited` event. 

Please, see how it works for masks in this file:  cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx 

image

Try to edit mask and press N after finish editing.

**Comment by KrishavRajSingh** [comment]
@bsekachev You may review it now.

**Comment by bsekachev** [comment]
Hi @KrishavRajSingh 

I see a problem here. Polygon editing is also affected. It finishes when pressing N (what is incorrect because polygon must be closed first)

**Comment by KrishavRajSingh** [comment]
One more thing,  wanted to run tests but I am not able to generate the cvat-sdk package code, this is giving me errors after I ran ./cvat-sdk/gen/generate.sh
image

**Comment by bsekachev** [comment]
You may to install sdk of necessary version using pip, you do not need to generate it

File: cvat-canvas/src/typescript/editHandler.ts [hunk 2]
```diff
@@ -380,6 +370,19 @@ export class EditHandlerImpl implements EditHandler {
...
+            const points = pointsToNumberArray(stringifiedPoints)
+                .slice(0, -2)
+                .map((coord: number): number => coord - offset);
+            if (points.length >= 2 * 2) { // minimumPoints * 2
+                const { state } = this.editData;
+                this.onEditDone(state, points);
+            }
+        }
+        this.isEditing = false;
         this.release();
```
[the remark this answers is not in the document]
Comment (KrishavRajSingh) [reply cvat-canvas/src/typescript/editHandler.ts:386]: Since the polygon editing was affected, i am thinking to add checktype for shape, something like this
`
private closeEditing(): void {
        if (this.isEditing && this.editData.state.shapeType === 'polyline') {
           ...
        } else {
            this.onEditDone(null, null);
        }
        this.isEditing = false;
        this.release();
    }
`
So I think I shall keep it outside.
I am open to suggestions.

File: cvat-canvas/src/typescript/editHandler.ts [hunk 3]
```diff
@@ -380,6 +368,21 @@ export class EditHandlerImpl implements EditHandler {
...
+                .slice(0, -2)
+                .map((coord: number): number => coord - offset);
+            if (points.length >= 2 * 2) { // minimumPoints * 2
+                const { state } = this.editData;
+                this.onEditDone(state, points);
+            }
+        } else {
+            this.onEditDone(null, null);
+        }
+        this.isEditing = false;
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/editHandler.ts:385]: - I believe we should set `this.isEditing = false` in `release` method
- I believe we should set `this.isEditing = true` in `initEditing` method

**Comment by bsekachev** [comment]
Hello,

There is still minor problem that does not exist in current develop branch.
When a polygon is being edited, and user presses **N**, polygon editing is cancelled (in `develop` nothing happens in this case). 

That may make some users to lose their progress when they accidentally click N button.

File: cvat-canvas/src/typescript/editHandler.ts (hunk 3 above)
Comment (bsekachev) [inline cvat-canvas/src/typescript/editHandler.ts:385]: Probably `release` shall be called inside the condition. Otherwise it leads to the issue, I described in the pull request with polygons

Comment (KrishavRajSingh) [reply cvat-canvas/src/typescript/editHandler.ts]: Release method needs to be called whenever a polyline is edited, so i think it should be outside. 

As for the issue, I fixed it by cheking the shapeType of the editHandler and pass `{enabled: false}` only if the shapetype is polyline in canvasview.ts. It shall work fine now.

**Comment by bsekachev** [comment]
Alright, thanks for the contribution!

**Review by bsekachev — APPROVED** [review]
