### PR TITLE
Exception 'Canvas is busy' when change frame during drag/resize a track

### LINKED ISSUE #8271: The box is thrown outside the frame at the moment of saving
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

If you drag the box and a save event occurs, it is thrown outside the frame

How to reproduce:

You can actually play this every time with CTRL+S while dragging the box.

### Expected Behavior

Nothing happaning

### Possible Solution

Resize the image.

### Context

Available in: at least 2.12 and up to 2.16.0

### Environment

```Markdown
commit 8ca0236135493d1873dff9a0627f64a14ba6ee18 (HEAD, tag: v2.16.0)
```

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Related #1371 (one more way to reproduce the issue) 
Resolved #8271

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

## Release Notes

- **Bug Fixes**
	- Resolved an issue causing an exception when changing frames during track dragging or resizing, improving user interaction.
	- Fixed a problem where shapes were incorrectly shifted during auto-save while dragging, ensuring shapes maintain their intended positions.

- **Improvements**
	- Enhanced drag-and-drop functionality by capturing initial position coordinates of shapes, allowing for a more intuitive experience during drag operations.

### CODE REVIEW

File: cvat-canvas/src/typescript/canvasView.ts [hunk 1]
```diff
@@ -1359,7 +1409,8 @@ export class CanvasViewImpl implements CanvasView, Listener {
                     onResizeEnd();
                     aborted = true;
                     this.resizableShape = null;
-                    // disable internal drag events of SVG.js
+                    // disable internal resize events of SVG.js
+                    // call chain is (mouseup -> SVG.handler.end -> SVG.handler.drag -> dragend)
```
Comment (bsekachev) [inline cvat-canvas/src/typescript/canvasView.ts:1413]:
```suggestion
                    // call chain is (mouseup -> SVG.handler.end -> SVG.handler.resize-> resizeend)
```
